#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/remotend/remotend /usr/bin/remotend
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/remotend.service ]; then
			rm /etc/systemd/system/remotend.service /usr/lib/systemd/system/remotend.service /usr/lib/systemd/user/remotend.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/remotend/files/systemd/remotend.service /usr/lib/systemd/system/remotend.service
		systemctl daemon-reload
		systemctl enable remotend
		systemctl start remotend
	fi
fi
