#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
        rm /usr/bin/remotend
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop remotend || true
			systemctl disable remotend || true
			rm /etc/systemd/system/remotend.service /usr/lib/systemd/system/remotend.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			ubuntuVersion=$(grep -oP 'VERSION_ID="\K[\d]+' /etc/os-release | bc -l)
			waylandSupportVersion=21
			if [ "$ubuntuVersion" != "" ] && [ "$ubuntuVersion" -ge "$waylandSupportVersion" ]
			then
				serverUser=$(ps -ef | grep -E 'remotend +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
				if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
				then
					systemctl --machine=${serverUser}@.host --user stop remotend >/dev/null 2>&1 || true
				fi
			fi
			rm /usr/lib/systemd/user/remotend.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
